language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: GvMyTtszJz4g6Y1LKwQPqfbE8HSzUoihD+NoC+DJ24dIr9czfJL+xti0qoiZ+btPybv9nu1LwyOwhyPppkiLymvWCo+RbL4KuPecv1HSqPN3U4XMSo90I0haD0Qd6sJa3L5OnLqXbdwabUcQwZc4YWIola/3yT7hNQOzYmn4qAcHYCubcsXX/IPaWVkCg/ELP93g56uEDV+3e8MenJ9MktXIuAXT4UEwRgX4+aHGQpp4MeAaTeqw1aip3CpnsS7tWAQw11Lb3Kyv7hJnSz6f+R2BFDghNC/uLwhtK63xBBzccoU758QghgEQOU8lpubw2vPqXs1naTIffIrB1bk8XOJhOmbi/YLWRSC/wQmb8X4vqT4rECp58e/IStg/ZxbC5zQ11V5xrcLvXr6F0hMHmTBUSQ06QFtzLp2ziGkdVcFCVMqyNTnUfQz5Abkh/04hpHnj1B8QxgYEf2rJNMDXzfbyvXLC5McPxP8u60Ds86VwJvI+cMJqig6ElO4xJ7Vo/+BaMT8Ub2rvjBX8UsDO6877WpNp2yvrxDUWP6utO7KBvFDVonc+4ryT7Nf83tepRF5TaBeTD5FHYgWxvRx+q4aimz64KUclAvclGhbGLr/nr122uAY8Z8yFrinWaPMxdEyAXLCiYwM0QpUBUdPlD5yf3ErttKmQVqwMO9KB4QM=
  app: dan-noteful-v4
  on:
    repo: thinkful-ei22/dan-noteful-4
